version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-multitenant
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
        - db-multitenant-data:/var/lib/postgresql/data
volumes:
  db-multitenant-data:
